export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    REFRESH: '/auth/refresh',
  },
  USERS: {
    LIST: '/users',
    SEARCH: '/users/search',
    DETAIL: (id: number | string) => `/users/${id}`,
    CREATE: '/users',
    UPDATE: (id: number | string) => `/users/${id}`,
    DELETE: (id: number | string) => `/users/${id}`,
  },
  DEPARTMENTS: {
    SEARCH: '/departments/search',
    DETAIL: (id: string) => `/departments/${id}`,
    CREATE: '/departments',
    UPDATE: (id: string) => `/departments/${id}`,
    DELETE: (id: string) => `/departments/${id}`,
  },
  POSITIONS: {
    SEARCH: '/positions/search',
    DETAIL: (id: string) => `/positions/${id}`,
    CREATE: '/positions',
    UPDATE: (id: string) => `/positions/${id}`,
    DELETE: (id: string) => `/positions/${id}`,
  },
  EMPLOYEES: {
    SEARCH: '/employees/search',
    DETAIL: (id: string) => `/employees/${id}`,
    CREATE: '/employees',
    UPDATE: (id: string) => `/employees/${id}`,
    DELETE: (id: string) => `/employees/${id}`,
  },
  CONTRACTS: {
    SEARCH: '/contracts/search',
    DETAIL: (id: string) => `/contracts/${id}`,
    CREATE: '/contracts',
    UPDATE: (id: string) => `/contracts/${id}`,
    UPLOAD: (id: string) => `/contracts/${id}/upload`,
  },
  ATTENDANCE: {
    SEARCH: '/attendance/search',
    DETAIL: (id: string) => `/attendance/${id}`,
    UPDATE: (id: string) => `/attendance/${id}`,
    TEMPLATE: '/attendance/template',
    IMPORT: '/attendance/import',
  },
  PAYROLL: {
    CALCULATE: '/payroll/calculate',
    SEARCH: '/payroll/search',
    DETAIL: (id: string) => `/payroll/${id}`,
    UPDATE: (id: string) => `/payroll/${id}`,
    DELETE: (id: string) => `/payroll/${id}`,
  },
  SALARY_PAYMENTS: {
    CREATE: '/salary-payments/create',
    SEARCH: '/salary-payments/search',
    DETAIL: (id: string) => `/salary-payments/${id}`,
  },
  CONFIG: {
    SALARY_FACTORS: '/config/salary-factors',
    TAX: '/config/tax',
    INSURANCE: '/config/insurance',
    HOLIDAYS: '/config/holidays',
  },
  REPORTS: {
    SALARY: '/reports/salary',
    DASHBOARD: '/reports/dashboard',
    EXPORT: '/reports/export',
  },
} as const
